### PR TITLE
Updated to Publishers v1.1 per action item from https://lists.oasis-o…

### PR DESCRIPTION
**Pull request by shudson310**
…pen.org/archives/docbook/201608/msg00010.html

### CODE REVIEW

**Comment by ndw** [comment]
Scott,

Did you pull an up-to-date repo for this? It fails because it takes too long to run all the tests. I swear I fixed this by having it only do a sampling of tests when it was running under Travis.

**Comment by shudson310** [comment]
Hi Norm,

I pulled it back in September? I only set the pull for the 2 files I changed: publishers.rnc and the Pygmallion sample.

--Scott

**Comment by ndw** [comment]
I committed a fix for the build issue. Can you rebase your pull request off the latest head?

**Comment by shudson310** [comment]
Norm, I tried to rebase my fork from the main Docbook master. The travis build still failed. I'm not sure what is going on here. Should I send you my latest publishers.rnc separately  to determine if that is the problem?

**Comment by ndw** [comment]
The problem now is that you have a failing test. The test publishers/test/fail/caution-001.xml is supposed to fail, because admonitions are not allowed. But it's passing. Is that an intentional change?

**Comment by shudson310** [comment]
Hi Norm, yes, per [https://sourceforge.net/p/docbook/publishers-rfe/7/] admonitions are now allowed in Publishers content.

**Comment by ndw** [comment]
Ok. So fix the test :-)

I think all you have to do is move the file from the 'fail' directory to the 'pass' directory. But if you run 'gradle' in the schemas directory, you should get a pass when you've fixed it.

**Comment by shudson310** [comment]
OK, will do. Thanks, Norm! I'm also adding the Pygmalion excerpt, since it tests validity of the stagedir elements.

**Comment by shudson310** [comment]
Admonitions are now allowed for Publishers.

--Scott

**Pull request merged**
